### ISSUE TITLE
Compatibility with docker-mac-net-connect

### ISSUE THREAD

**Issue by alexandertsukanov** [Mahoney/docker-etc-hosts#1] opened 2022-05-28 07:02 UTC
Hi, @Mahoney !
I found you have the library which can help to automate the workflow of the binding IP addresses with Docker container names
I have tried on my mac to use your lib but without any success.  I am wondering is it possible to use it without `tuntap`? 
Thanks.

**Comment by Mahoney** [comment] 2022-05-28 10:08
The problem isn't with docker-mac-net-connect or tuntap - I tried to switch to zsh from bash, in order to work on modern macs, but clearly failed in my syntax transfer.

Now that docker-mac-net-connect exists I'll revisit it - I rather let it lie because on an M1 Mac I couldn't access the containers by IP anyway.

**Comment by Mahoney** [comment] 2022-05-28 10:33
Actually looking at it I switched back to bash but I'm using syntax that doesn't work in bash 3, which is the default bash that root will be using on a mac and the script runs as root :-/. Which was why I tried & failed to switch to zsh...

Know of a tool that will help me work out what I need to change to make it bash 3 compatible?

**Comment by Mahoney** [comment] 2022-05-28 13:14
Closing in favour of #2

**Closed as completed by Mahoney** 2022-05-28 13:14 UTC
